"""sync main schema for seeders

Revision ID: 99536bbf9625
Revises: 20260507_0001
Create Date: 2026-05-13 15:01:20.770840
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '99536bbf9625'
down_revision = '20260507_0001'
branch_labels = None
depends_on = None


def _columns(table_name: str) -> set[str]:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return {column["name"] for column in inspector.get_columns(table_name)}


def _indexes(table_name: str) -> set[str]:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return {index["name"] for index in inspector.get_indexes(table_name)}


def _foreign_key_exists(table_name: str, constrained_columns: list[str]) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return any(
        foreign_key.get("constrained_columns") == constrained_columns
        for foreign_key in inspector.get_foreign_keys(table_name)
    )


def _add_column_if_missing(table_name: str, column: sa.Column) -> None:
    if column.name in _columns(table_name):
        return
    op.add_column(table_name, column)


def _create_index_if_missing(index_name: str, table_name: str, columns: list[str]) -> None:
    if index_name in _indexes(table_name):
        return
    op.create_index(index_name, table_name, columns, unique=False)


def upgrade() -> None:
    _add_column_if_missing('boards', sa.Column('parent_entity_type', sa.String(length=32), nullable=True))
    _add_column_if_missing('boards', sa.Column('parent_entity_id', sa.Uuid(), nullable=True))
    _add_column_if_missing('boards', sa.Column('vice_chairperson_id', sa.UUID(), nullable=True))
    _add_column_if_missing('boards', sa.Column('member_count', sa.Integer(), nullable=True))
    _add_column_if_missing('boards', sa.Column('quorum', sa.Integer(), nullable=True))
    _add_column_if_missing('boards', sa.Column('standard_term_years', sa.Integer(), nullable=True))
    _add_column_if_missing('boards', sa.Column('max_terms', sa.Integer(), nullable=True))
    _add_column_if_missing('boards', sa.Column('show_member_terms', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    _create_index_if_missing('ix_boards_parent_entity', 'boards', ['parent_entity_type', 'parent_entity_id'])
    _create_index_if_missing(op.f('ix_boards_parent_entity_id'), 'boards', ['parent_entity_id'])
    _create_index_if_missing(op.f('ix_boards_parent_entity_type'), 'boards', ['parent_entity_type'])
    _create_index_if_missing(op.f('ix_boards_vice_chairperson_id'), 'boards', ['vice_chairperson_id'])
    if not _foreign_key_exists('boards', ['vice_chairperson_id']):
        op.create_foreign_key(
            'fk_boards_vice_chairperson_id_persons',
            'boards',
            'persons',
            ['vice_chairperson_id'],
            ['id'],
            ondelete='SET NULL',
        )
    _add_column_if_missing('staff_assignments', sa.Column('term_years', sa.Integer(), nullable=True))
    _add_column_if_missing('staff_assignments', sa.Column('term_renewable', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    _add_column_if_missing('staff_assignments', sa.Column('show_term_dates', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('staff_assignments', 'hierarchy_level',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_assignments', 'hierarchy_level',
               existing_type=sa.INTEGER(),
               server_default=sa.text('8'),
               existing_nullable=False)
    op.drop_column('staff_assignments', 'show_term_dates')
    op.drop_column('staff_assignments', 'term_renewable')
    op.drop_column('staff_assignments', 'term_years')
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_index(op.f('ix_boards_vice_chairperson_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_parent_entity_type'), table_name='boards')
    op.drop_index(op.f('ix_boards_parent_entity_id'), table_name='boards')
    op.drop_index('ix_boards_parent_entity', table_name='boards')
    op.drop_column('boards', 'show_member_terms')
    op.drop_column('boards', 'max_terms')
    op.drop_column('boards', 'standard_term_years')
    op.drop_column('boards', 'quorum')
    op.drop_column('boards', 'member_count')
    op.drop_column('boards', 'vice_chairperson_id')
    op.drop_column('boards', 'parent_entity_id')
    op.drop_column('boards', 'parent_entity_type')
    # ### end Alembic commands ###
