FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends bash curl gcc libpq-dev && rm -rf /var/lib/apt/lists/*

COPY common /common
RUN pip install --no-cache-dir -e /common

COPY research/ .
RUN pip install --no-cache-dir -e .

EXPOSE 8001

CMD ["uvicorn", "wsgi:app", "--host", "0.0.0.0", "--port", "8001"]
