"use client";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { FileBarChart, Printer, RefreshCw } from "lucide-react";
import { Button, Card, CardContent, CardHeader, CardTitle, Checkbox, Select, SelectContent, SelectItem, SelectTrigger, SelectValue, Skeleton } from "@ksu/ui/components";
import { schoolPortalApi, schoolPortalQueryKeys, type SchoolPortalDashboardRange } from "@ksu/api-client";
import { useSchoolPortal } from "./school-portal-provider";
import { SchoolWorkspace, SchoolWorkspaceHeader } from "./shared/school-workspace";

const sections = ["School summary", "Academic portfolio", "People & leadership", "Content & publications", "Inquiries", "Documents & evidence", "Recent activity"];
export function SchoolReportsPage() { const { school } = useSchoolPortal(); const [selected, setSelected] = useState(sections); const [presentation, setPresentation] = useState(false); const [range, setRange] = useState<SchoolPortalDashboardRange>("30d"); const query = useQuery({ queryKey: schoolPortalQueryKeys.dashboard(school.id, range), queryFn: async () => (await schoolPortalApi.dashboard(range)).data }); return <SchoolWorkspace><SchoolWorkspaceHeader eyebrow="School administration" title={presentation ? "Report presentation" : "Reports"} description="Prepare an evidence-led report from authorized school data." icon={FileBarChart} actions={<div className="flex gap-2"><Button variant="outline" onClick={() => void query.refetch()} disabled={query.isFetching}><RefreshCw className="mr-2 size-4"/>Refresh</Button><Button onClick={() => { setPresentation(true); window.setTimeout(() => window.print(), 0); }} disabled={!query.data}><Printer className="mr-2 size-4"/>{presentation ? "Print report" : "Present report"}</Button></div>} />{query.isPending ? <Skeleton className="h-72"/> : <div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>{presentation ? "Selected report sections" : "Report sections"}</CardTitle></CardHeader><CardContent className="space-y-3">{sections.map((section) => <label key={section} className="flex items-center gap-3 rounded-md border p-3"><Checkbox checked={selected.includes(section)} disabled={presentation} onCheckedChange={(checked) => setSelected((current) => checked ? [...current, section] : current.filter((item) => item !== section))}/><span>{section}</span></label>)}{presentation ? <p className="pt-2 text-xs text-muted-foreground">Read-only presentation of the latest authorized school data.</p> : null}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Report context</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><Select value={range} onValueChange={(value) => setRange(value as SchoolPortalDashboardRange)} disabled={presentation}><SelectTrigger aria-label="Reporting period"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="30d">Last 30 days</SelectItem><SelectItem value="90d">Last 90 days</SelectItem><SelectItem value="12m">Last 12 months</SelectItem></SelectContent></Select><p className="text-muted-foreground">School: <strong>{school.name}</strong></p><p className="rounded-md bg-muted/50 p-3 text-xs">Source: school dashboard aggregation · Updated {query.data ? new Date(query.data.generated_at).toLocaleString() : "—"}</p><Button variant="outline" className="w-full" disabled={!query.data} onClick={() => { setPresentation(true); window.setTimeout(() => window.print(), 0); }}>Download PDF</Button><Button variant="outline" className="w-full" disabled={!query.data} onClick={() => { window.location.assign(schoolPortalApi.reportExportUrl(range, "csv")); }}>Export CSV</Button></CardContent></Card></div>}</SchoolWorkspace>; }
