global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: ksu-http-services
    metrics_path: /metrics
    static_configs:
      - targets:
          - main:8000
          - research:8001
          - library:8002
          - heri:8003

  - job_name: ksu-celery-workers
    static_configs:
      - targets:
          - celery-main:9100
          - celery-library:9101
          - celery-research:9102
          - celery-heri:9103
