"""Current official-site news and events captured on 2026-09-08.

The entries below are limited to items visible on the live Kisii University
homepage/events pages and their official detail pages.  They supplement the
previous verified snapshot without replacing historical records.
"""

from __future__ import annotations

from datetime import datetime
from zoneinfo import ZoneInfo


EAT = ZoneInfo("Africa/Nairobi")


LIVE_SITE_NEWS_UPDATES_20260908 = [
    {
        "title": "Elite Savers donate segregated Waste Bins to KSU",
        "category": "NEWS",
        "summary": "Elite Savers donated segregated waste bins to Kisii University as part of a cleaner, greener and more sustainable campus.",
        "plain_text": "Today, the Vice Chancellor hosted officials from Elite Savers, CBO, who donated segregated waste bins to the University. Kisii University linked the initiative to tree planting, landscaping, paving of internal roads and floral beautification, and reaffirmed its commitment to a clean, green and aesthetically inspiring environment.",
        "published_at": datetime(2026, 9, 7, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/elite-savers-donate-segregated-waste-bins-to-ksu",
        "source_image_url": "https://kisiiuniversity.ac.ke/resources/6a9e9fc7c144d.jpeg",
        "display_order": 1,
        "is_featured": True,
    },
    {
        "title": "The 1st Gusii Education Stakeholders Convention",
        "category": "NEWS",
        "summary": "Kisii University welcomed participants to the first Gusii Education Stakeholders Convention.",
        "plain_text": "The Vice Chancellor welcomes you all to Kisii University for the 1st edition of the Gusii Education Stakeholders Convention. Are you ready to re-imagine your future?",
        "published_at": datetime(2026, 9, 7, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/the-1st-gusii-education-stakeholders-convention",
        "source_image_url": "https://kisiiuniversity.ac.ke/resources/6a9e9fc7c144d.jpeg",
        "display_order": 2,
        "is_featured": True,
    },
    {
        "title": "TENDER FOR PROVISION OF INTERNET SERVICES",
        "category": "TENDERS",
        "summary": "Kisii University published a tender for provision of internet services.",
        "plain_text": "For More Information visit PROCUREMENT PORTAL.",
        "published_at": datetime(2026, 9, 3, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/tender-for-provision-of-internet-services",
        "source_image_url": "https://kisiiuniversity.ac.ke/resources/6a992d311cb17.jpeg",
        "display_order": 3,
        "is_featured": False,
    },
    {
        "title": "Welcome to Kisii University 2026",
        "category": "NEWS",
        "summary": "Kisii University presents its campus as an environment where academic ambitions, social connections and career possibilities can flourish.",
        "plain_text": "At Kisii University, we believe that great journeys need more than classrooms, they need an environment where minds can breathe, dreams can take root, and possibilities can flourish. Set within a serene and naturally inspiring environment, we provide the space, people and opportunities to help you pursue your academic ambitions, build meaningful social connections and chart a rewarding career path. We are Kisii University. Where ambition finds its home, and possibilities find their wings.",
        "published_at": datetime(2026, 9, 2, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/welcome-to-kisii-university-2026",
        "source_image_url": "https://kisiiuniversity.ac.ke/resources/6a98a2e8c3120.jpeg",
        "display_order": 4,
        "is_featured": False,
    },
    {
        "title": "Validation workshop on language Education (foundational literacy) thematic areas and research Questions",
        "category": "NEWS",
        "summary": "The HERI-Africa language Education Chair held a stakeholder validation workshop on foundational-literacy research themes and questions.",
        "plain_text": "The HERI-Africa language Education Chair engaged with stakeholders in a validation workshop to deliberate on the research questions on language education. The session focused on the presentation and validation of five proposed thematic areas under the Research Chair, with stakeholders providing critical feedback intended to sharpen the research focus, reframe research questions, and ground the study in policy-relevant, data-driven inquiry. A cross-cutting theme was the need for systematic, policy-level research backed by robust national data.",
        "published_at": datetime(2026, 9, 2, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/validation-workshop-on-language-education-foundational-literacy-thematic-areas-and-research-questions",
        "source_image_url": "https://kisiiuniversity.ac.ke/storage/public/resources/EmjxH2F8TadmnDCMyyb3wtJCxaNzIUZblx0bONZu.jpg",
        "display_order": 5,
        "is_featured": False,
    },
    {
        "title": "Our Own Alex Mutua Recipient of JICA Scholarship 2025/26",
        "category": "NEWS",
        "summary": "Kisii University nutrition and dietetics student Alex Mutua was recognised among the JICA Scholarship 2025/26 recipients and is set to pursue a two-year master’s programme in Japan.",
        "plain_text": "The Vice Chancellor joined the send-off ceremony for the JICA Scholarship 2025/26 recipients, organised by JICA and the Embassy of Japan. Kisii University's Alex Mutua of Nutrition and Dietetics departs on 12th September 2026 for Japan to pursue a two-year master's programme.",
        "published_at": datetime(2026, 8, 29, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/our-own-alex-mutua-recipient-of-jica-scholarship-202526",
        "source_image_url": "https://kisiiuniversity.ac.ke/resources/6a93235df2610.jpeg",
        "display_order": 6,
        "is_featured": False,
    },
    {
        "title": "INTER/INTRA SCHOOL TRANSFERS SEPT 2026",
        "category": "NEWS",
        "summary": "Kisii University published the September 2026 inter-school and intra-school transfer notice.",
        "plain_text": "Kisii University published the September 2026 inter-school and intra-school transfer notice. Applicants should follow the official University process and notices for the applicable transfer information.",
        "published_at": datetime(2026, 8, 29, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/interintra-school-transfers-sept-2026",
        "source_image_url": "https://kisiiuniversity.ac.ke/resources/6a9320f699fd4.jpeg",
        "display_order": 7,
        "is_featured": False,
    },
    {
        "title": "2026 Matriculation Ceremony",
        "category": "NEWS",
        "summary": "The Vice Chancellor led the 2026 First Years Matriculation Ceremony at the Chancellor's Pavilion.",
        "plain_text": "In a powerful celebration of promise, purpose and possibility, the Vice Chancellor led the 2026 First Years Matriculation Ceremony at the Chancellor's Pavilion. The University welcomed a new generation of scholars and affirmed its commitment to nurture their dreams, shape their talents and prepare them for a world without borders.",
        "published_at": datetime(2026, 8, 25, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/2026-matriculation-ceremony",
        "source_image_url": "https://kisiiuniversity.ac.ke/resources/6a8defb8af4b4.jpeg",
        "display_order": 8,
        "is_featured": False,
    },
    {
        "title": "External Advertisement Teaching Positions August 2026",
        "category": "NEWS & CAREERS",
        "summary": "Kisii University published an external advertisement for teaching positions in August 2026.",
        "plain_text": "Visit our career portal for more information.",
        "published_at": datetime(2026, 8, 24, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/external-advertisement-teaching-positions-august-2026",
        "source_image_url": "https://kisiiuniversity.ac.ke/resources/6a8c521247b53.jpeg",
        "display_order": 9,
        "is_featured": False,
    },
    {
        "title": "Session Reporting Sem 1 2026/2027",
        "category": "NEWS",
        "summary": "Kisii University published the session-reporting notice for Semester One of the 2026/2027 academic year.",
        "plain_text": "Kisii University published the session-reporting notice for Semester One of the 2026/2027 academic year. Students should follow the official University notice for reporting arrangements.",
        "published_at": datetime(2026, 8, 23, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/session-reporting-sem-1-20262027",
        "source_image_url": "https://kisiiuniversity.ac.ke/resources/6a8b417827a98.png",
        "display_order": 10,
        "is_featured": False,
    },
    {
        "title": "A Call to Host the HERI Africa Research Chair on African Perspectives and Theories for Education",
        "category": "NEWS",
        "summary": "A Call to Host the HERI Africa Research Chair on African Perspectives and Theories for Education.",
        "plain_text": "Posted on Aug 20, 2026 by Kisii University.",
        "published_at": datetime(2026, 8, 20, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/a-call-to-host-the-heri-africa-research-chair-on-african-perspectives-and-theories-for-education",
        "source_image_url": "https://kisiiuniversity.ac.ke/storage/public/resources/E6z8oxsMGWcWOcvAqxGiZXmmqidk8xeMrcVsuSqr.jpg",
        "display_order": 11,
        "is_featured": False,
    },
    {
        "title": "A Call to Host the HERI Africa Research Chair on Gender, Equity and Social Inclusion in Education",
        "category": "NEWS",
        "summary": "A Call to Host the HERI Africa Research Chair on Gender, Equity and Social Inclusion in Education.",
        "plain_text": "Posted on Aug 20, 2026 by Kisii University.",
        "published_at": datetime(2026, 8, 20, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/a-call-to-host-the-heri-africa-research-chair-on-gender-equity-and-social-inclusion-in-education",
        "source_image_url": "https://kisiiuniversity.ac.ke/storage/public/resources/o4tbD6cqBcfQ3bKtXjSqxoMUZ4Z1lNsdmOww54nq.jpg",
        "display_order": 12,
        "is_featured": False,
    },
    {
        "title": "VC and County leadership explore creating pedestrian walkway to Campus",
        "category": "NEWS",
        "summary": "VC and County leadership explore creating pedestrian walkway to Campus.",
        "plain_text": "In a deliberate step towards making our Student's daily movement safer and more comfortable, the Vice Chancellor hosted County leadership to explore infrastructure solutions, including the creation of a dedicated pedestrian pathway running from the Main University gate throughout the University Way stretch. This initiative will provide a safer alternative for the increased foot traffic experienced during the morning and evening hours, particularly as our students travel to and from town for academic and social engagements. Together, we are building an environment where every student can learn, thrive, and move with confidence. At Kisii University, the safety and welfare of our students remain at the heart of everything we do.",
        "published_at": datetime(2026, 8, 17, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/vc-and-county-leadership-explore-creating-pedestrian-walkway-to-campus",
        "source_image_url": "https://kisiiuniversity.ac.ke/resources/6a8372e1e7cfc.jpeg",
        "display_order": 13,
        "is_featured": False,
    },
    {
        "title": "Communique from the Registrar AA on Academic Calendar 2026-2027",
        "category": "NEWS",
        "summary": "Communique from the Registrar AA on Academic Calendar 2026-2027.",
        "plain_text": "Posted on Aug 12, 2026 by Kisii University.",
        "published_at": datetime(2026, 8, 12, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/communique-from-the-registrar-aa-on-academic-calendar-2026-2027",
        "source_image_url": "https://kisiiuniversity.ac.ke/resources/6a7be6d4723ad.jpeg",
        "display_order": 14,
        "is_featured": False,
    },
    {
        "title": "CALL FOR APPLICATIONS: 2026/2027 LANGUAGE EDUCATION POSTGRADUATE SCHOLARSHIPS IN FOUNDATIONAL LITERACY",
        "category": "ACADEMICS",
        "summary": "Kisii University published a call for applications for 2026/2027 language education postgraduate scholarships in foundational literacy.",
        "plain_text": "Posted on Jul 30, 2026 by Kisii University. ACADEMICS. OPEN THE FULL ADVERT. POSTGRADUATE APPLICATION FORMS. REFEEE CONFIDENTIAL REPORT.",
        "published_at": datetime(2026, 7, 30, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/call-for-applications-20262027-language-education-postgraduate-scholarships-in-foundational-literacy",
        "source_image_url": "https://kisiiuniversity.ac.ke/storage/public/resources/UN1Sy5wVsSJlnopFXM0Lb3b3oS8WX9PXHmnTWYzB.png",
        "display_order": 15,
        "is_featured": False,
    },
    {
        "title": "KSU Students Return from 21 Day Medical School expedition at University of Manchester",
        "category": "NEWS",
        "summary": "Kisii University Medicine students returned from a 21-day medical school expedition at the University of Manchester.",
        "plain_text": "They went, they saw, they conquered. After an enriching 21-day medical school expedition at the University of Manchester, our Medicine students have returned home carrying more than knowledge. They return with new connections, fresh perspectives, unforgettable experiences, and a deeper understanding of medicine in a global context. This journey reminded us that learning knows no borders, and medicine is a language that connects us all. At Kisii University, we are not only preparing doctors for today, we are nurturing globally minded healthcare leaders for tomorrow. We are Kisii University. We are borderless.",
        "published_at": datetime(2026, 8, 9, 12, 0, tzinfo=EAT),
        "source_url": "https://kisiiuniversity.ac.ke/blog/ksu-students-return-from-21-day-medical-school-expedition-at-university-of-manchester",
        "source_image_url": "https://kisiiuniversity.ac.ke/storage/public/resources/4Wk5sDm9p0G3Gzj2AXJHIufYOa2xFerUYEMACCho.jpg",
        "gallery_image_urls": [
            "https://kisiiuniversity.ac.ke/resources/6a78f6fa03310.jpeg",
            "https://kisiiuniversity.ac.ke/resources/6a78f6fa7030b.jpeg",
            "https://kisiiuniversity.ac.ke/resources/6a78f6fa80655.jpeg",
            "https://kisiiuniversity.ac.ke/resources/6a78f6fa8fdbc.jpeg",
            "https://kisiiuniversity.ac.ke/resources/6a78f6fa9f050.jpeg",
            "https://kisiiuniversity.ac.ke/resources/6a78f6faaf2e8.jpeg",
            "https://kisiiuniversity.ac.ke/resources/6a78f6fabd364.jpeg",
            "https://kisiiuniversity.ac.ke/resources/6a78f6fac9d87.jpeg",
            "https://kisiiuniversity.ac.ke/resources/6a78f6fad78b5.jpeg",
            "https://kisiiuniversity.ac.ke/resources/6a78f6fae523f.jpeg",
        ],
        "display_order": 16,
        "is_featured": False,
    },
]


LIVE_SITE_EVENT_UPDATES_20260908 = [
    {
        "title": "Gusii Education Stakeholders Convention",
        "summary": "The Vice Chancellor welcomes you all to Kisii University for the 1st edition of the Gusii Education Stakeholders Convention. Are you ready to re-imagine your future?",
        "plain_text": "The Vice Chancellor welcomes you all to Kisii University for the 1st edition of the Gusii Education Stakeholders Convention. Are you ready to re-imagine your future?",
        "start_date": datetime(2026, 9, 10, 8, 0, tzinfo=EAT),
        "end_date": datetime(2026, 9, 10, 17, 0, tzinfo=EAT),
        "location": None,
        "source_url": "https://kisiiuniversity.ac.ke/event/gusii-education-stakeholders-convention",
        "source_image_url": "https://kisiiuniversity.ac.ke/storage/events/images/aQ3zC61gUmDgjXDy4uBWHGmhLHNMjaiE6ojEpt4o.jpg",
        "display_order": 1,
        "is_featured": False,
    },
    {
        "title": "Campus Spark Innovation Festival 2026",
        "summary": "Something big is coming to Kisii University next week. Are you ready for the Campus Spark Innovation Festival.",
        "plain_text": "Something big is coming to Kisii University next week. Are you ready for the Campus Spark Innovation Festival.",
        "start_date": datetime(2026, 7, 21, 9, 0, tzinfo=EAT),
        "end_date": datetime(2026, 7, 21, 17, 0, tzinfo=EAT),
        "location": "Kisii Universty Senate Chambers",
        "source_url": "https://kisiiuniversity.ac.ke/event/campus-spark-innovation-festival-2026",
        "source_image_url": "https://kisiiuniversity.ac.ke/storage/events/images/eJvf5wnwgTMV2FyFiR61qonTDZlU5aOC7vXQqykF.jpg",
        "display_order": 2,
        "is_featured": False,
    },
    {
        "title": "Kongamano la Chamaka 2026",
        "summary": "Chuo Kikuu cha Kisii kinajivunia kuwa mwenyeji wa Mkutano wa CHAKAMA 2026, utakaofanyika hapa chuoni mwezi ujao. Jiandae kushuhudia mkusanyiko wa wasomi, watafiti na wadau mashuhuri wa lugha ya Kiswahili wakijadili njia bora za kuiendeleza lugha ya Kiswahili katika karne ya ishirini na moja na kuimarisha mchango wake katika elimu, utafiti, teknolojia na maendeleo ya jamii. Karibu tuungane katika kongamano hili muhimu linalolenga kuinua hadhi na thamani ya Kiswahili katika ngazi za kitaifa na kimataifa.",
        "plain_text": "Chuo Kikuu cha Kisii kinajivunia kuwa mwenyeji wa Mkutano wa CHAKAMA 2026, utakaofanyika hapa chuoni mwezi ujao. Jiandae kushuhudia mkusanyiko wa wasomi, watafiti na wadau mashuhuri wa lugha ya Kiswahili wakijadili njia bora za kuiendeleza lugha ya Kiswahili katika karne ya ishirini na moja na kuimarisha mchango wake katika elimu, utafiti, teknolojia na maendeleo ya jamii. Karibu tuungane katika kongamano hili muhimu linalolenga kuinua hadhi na thamani ya Kiswahili katika ngazi za kitaifa na kimataifa.",
        "start_date": datetime(2026, 8, 6, 9, 0, tzinfo=EAT),
        "end_date": datetime(2026, 8, 6, 17, 0, tzinfo=EAT),
        "location": "Ukumbi Mpya",
        "source_url": "https://kisiiuniversity.ac.ke/event/kongamano-la-chamaka-2026",
        "source_image_url": "https://kisiiuniversity.ac.ke/storage/events/images/URB3l8b3ZjvXpbkvbk6eT3i0Ju8CgIt4MvIgWpmv.jpg",
        "display_order": 3,
        "is_featured": False,
    },
    {
        "title": "6th International Nutrition and Dietetics Scientific Conference",
        "summary": "The sixth International Nutrition and Dietetics Scientific Conference will be held at Kisii University from 9 to 13 November 2026 in a hybrid format.",
        "plain_text": "The 6th International Nutrition and Dietetics Scientific Conference will bring together nutrition and dietetics professionals, researchers, policymakers and other stakeholders at Kisii University. The conference theme is Excellence in Nutrition Practice: Science, Innovation and Impact.",
        "start_date": datetime(2026, 11, 9, 8, 0, tzinfo=EAT),
        "end_date": datetime(2026, 11, 13, 17, 0, tzinfo=EAT),
        "location": "Kisii University, Kenya (hybrid)",
        "source_url": "https://kisiiuniversity.ac.ke/our_events",
        "source_image_url": "https://kisiiuniversity.ac.ke/resources/6a9e9fc7c144d.jpeg",
        "registration_url": "https://conferences.kndi.institute/series/6",
        "display_order": 4,
        "is_featured": True,
    },
]


__all__ = ["LIVE_SITE_NEWS_UPDATES_20260908", "LIVE_SITE_EVENT_UPDATES_20260908"]
