"""Programme catalogue sourced from the official Kisii University course brochure."""

from __future__ import annotations

from collections.abc import Iterable

BROCHURE_URL = "https://kisiiuniversity.ac.ke/storage/public/downloads//KISII%20UNIVERSITY%20COURSE%20BROCHURE.pdf"


def _fees(amount: int, display: str) -> dict[str, object]:
    return {"amount": amount, "currency": "KES", "period": "per_year", "display": display}


def _expand_programmes(
    *,
    programmes: Iterable[tuple[str, str]],
    level: str,
    mode_of_study: str,
    duration: str,
    entry_requirements: str,
    fees_structure: dict[str, object] | None = None,
    intake_months: tuple[str, ...] = (),
) -> list[dict[str, object]]:
    return [
        {
            "name": name,
            "department_code": department_code,
            "level": level,
            "mode_of_study": mode_of_study,
            "duration": duration,
            "entry_requirements": entry_requirements,
            "fees_structure": fees_structure,
            "intake_months": list(intake_months),
        }
        for name, department_code in programmes
    ]


BROCHURE_PROGRAMMES: list[dict[str, object]] = [
    *_expand_programmes(
        programmes=(
            ("Bachelor of Medicine and Bachelor of Surgery", "MED"),
        ),
        level="undergraduate",
        mode_of_study="full_time",
        duration="6 years",
        entry_requirements=(
            "KCSE mean grade B (Plain) with B (Plain) in each cluster subject, or equivalent A-Level, diploma, or biological sciences degree progression routes as published in the official brochure."
        ),
        fees_structure=_fees(400000, "Ksh. 400,000 per year"),
        intake_months=("September",),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Laws", "LAW"),
        ),
        level="undergraduate",
        mode_of_study="full_time",
        duration="4 years",
        entry_requirements="KCSE mean grade C+ with B (Plain) in English or Kiswahili, or at least 3 principal passes in KACE, or a bachelor's degree from a recognized university.",
        fees_structure=_fees(160000, "Ksh. 160,000 per year"),
        intake_months=("September",),
    ),
    *_expand_programmes(
        programmes=(
            ("Diploma in Laws", "LAW"),
        ),
        level="diploma",
        mode_of_study="full_time",
        duration="2 years",
        entry_requirements="KCSE mean grade C (Plain) with C+ in English or Kiswahili, or one principal pass in KACE, or a pass in an accredited certificate of law course or certificate of experiential learning recognized by the Council of Legal Education.",
        fees_structure=_fees(63400, "Ksh. 63,400 per year"),
        intake_months=("September",),
    ),
    *_expand_programmes(
        programmes=(
            ("PhD in Curriculum Studies", "CIM"),
            ("PhD in Educational Management", "EDFAPE"),
            ("PhD in Educational Foundations", "EDFAPE"),
            ("PhD in Educational Psychology", "ECDESNEEPSC"),
            ("PhD in Early Childhood Development Education", "ECDESNEEPSC"),
            ("PhD in Special Needs Education", "ECDESNEEPSC"),
            ("PhD in Educational Counseling Psychology", "ECDESNEEPSC"),
        ),
        level="phd",
        mode_of_study="full_time_part_time",
        duration="3 years",
        entry_requirements="Holder of a master's degree in a relevant field or its equivalent from a recognized institution.",
        fees_structure=_fees(150000, "Ksh. 150,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Master of Education in Curriculum and Instruction", "CIM"),
            ("Master of Education in Administration", "EDFAPE"),
            ("Master of Education in Planning and Economics", "EDFAPE"),
            ("Master of Education in Sociology", "EDFAPE"),
            ("Master of Education in Philosophy", "EDFAPE"),
            ("Master of Education in Comparative Education", "EDFAPE"),
            ("Master of Education in History of Education", "EDFAPE"),
            ("Master of Education in Educational Psychology", "ECDESNEEPSC"),
            ("Master of Education in Guidance and Counseling", "ECDESNEEPSC"),
            ("Master of Education in Special Needs Education", "ECDESNEEPSC"),
            ("Master of Education in Early Childhood Development Education", "ECDESNEEPSC"),
        ),
        level="masters",
        mode_of_study="full_time_part_time",
        duration="2 years",
        entry_requirements="Bachelor's degree with at least Second Class Upper or equivalent from a recognized university, or Lower Second Class with at least two years relevant experience.",
        fees_structure=_fees(100000, "Ksh. 100,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Education (Arts)", "CIM"),
        ),
        level="undergraduate",
        mode_of_study="full_time_part_time",
        duration="4 years",
        entry_requirements="KCSE mean grade C+ with C+ in two preferred teaching subjects, D+ in Mathematics, and C Plain in English, or equivalent diploma or principal pass routes as published in the brochure.",
        fees_structure=_fees(88000, "Ksh. 88,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Education (Science)", "CIM"),
        ),
        level="undergraduate",
        mode_of_study="full_time",
        duration="4 years",
        entry_requirements="KCSE mean grade C+ with C+ in two preferred teaching subjects, C Plain in Mathematics, and C Plain in English, or equivalent diploma or principal pass routes.",
        fees_structure=_fees(96000, "Ksh. 96,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Education (Primary Option)", "ECDESNEEPSC"),
            ("Bachelor of Education (Early Childhood Development Education)", "ECDESNEEPSC"),
            ("Bachelor of Education (Special Needs Education)", "ECDESNEEPSC"),
        ),
        level="undergraduate",
        mode_of_study="full_time",
        duration="4 years",
        entry_requirements="KCSE mean grade C+ with the subject and specialization thresholds published for each education pathway, or equivalent diploma progression routes recognized by the University.",
        fees_structure=_fees(88500, "Ksh. 88,500 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Diploma in Education Arts", "CIM"),
        ),
        level="diploma",
        mode_of_study="full_time",
        duration="3 years",
        entry_requirements="Mean grade C+ in KCSE with C+ in specialization subjects, C Plain in Mathematics, and C Plain in English.",
        fees_structure=_fees(54000, "Ksh. 54,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Post Graduate Diploma in Education", "CIM"),
        ),
        level="postgraduate_diploma",
        mode_of_study="full_time",
        duration="1 year",
        entry_requirements="First degree from a recognized university with two teaching subjects of C+ and above.",
        fees_structure=_fees(70000, "Ksh. 70,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("PhD in Agricultural Education and Extension", "AGEDX"),
            ("PhD in Agricultural Extension and Rural Development", "AGEDX"),
            ("PhD in Natural Resource Management", "NRES"),
            ("PhD in Environmental Science", "NRES"),
            ("PhD in Fisheries", "AAS"),
            ("PhD in Limnology", "AAS"),
            ("PhD in Agricultural and Applied Economics", "AGECO"),
            ("PhD in Agronomy", "AGRSCI"),
            ("PhD in Sustainable Agriculture", "AGRSCI"),
        ),
        level="phd",
        mode_of_study="full_time_part_time",
        duration="3 years",
        entry_requirements="Holder of a master's degree in a relevant field or its equivalent from a recognized institution.",
        fees_structure=_fees(150000, "Ksh. 150,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("MSc in Agricultural Education", "AGEDX"),
            ("MSc in Agricultural Extension", "AGEDX"),
            ("MSc in Agricultural and Applied Economics", "AGECO"),
            ("MSc in Natural Resource Management", "NRES"),
            ("MSc in Environmental Science and Water Resource Management", "NRES"),
            ("MSc in Agronomy", "AGRSCI"),
            ("MSc in Sustainable Agriculture", "AGRSCI"),
            ("MSc in Limnology", "AAS"),
            ("MSc in Fisheries", "AAS"),
            ("MSc in Aquaculture", "AAS"),
            ("MSc in Livestock Production Systems", "AGRSCI"),
        ),
        level="masters",
        mode_of_study="full_time_part_time",
        duration="2 years",
        entry_requirements="Bachelor's degree in a related field with Second Class Upper Division or Lower Division with two years working experience.",
        fees_structure=_fees(120000, "Ksh. 120,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Agribusiness Management", "AGECO"),
            ("Bachelor of Science in Agricultural Economics", "AGECO"),
            ("Bachelor of Science in Agricultural Education and Extension", "AGEDX"),
            ("Bachelor of Science in Agriculture", "AGRSCI"),
            ("Bachelor of Science in Environmental Sciences", "NRES"),
            ("Bachelor of Science in Natural Resource Management", "NRES"),
            ("Bachelor of Science in Applied Aquatic Sciences", "AAS"),
            ("Bachelor of Science in Fisheries and Aquaculture", "AAS"),
            ("Bachelor of Science in Animal Science", "AGRSCI"),
            ("Bachelor of Science in Agricultural Extension and Rural Development", "AGEDX"),
            ("Bachelor of Science in Horticulture", "AGRSCI"),
            ("Bachelor of Science in Soil Environment and Land Resource Management", "AGRSCI"),
            ("Bachelor of Science in Aquatic Sciences", "AAS"),
        ),
        level="undergraduate",
        mode_of_study="full_time",
        duration="4 years",
        entry_requirements="KCSE mean grade C+ with subject combinations and diploma progression routes as specified for the respective agriculture and natural resource programmes in the official brochure.",
        fees_structure=_fees(96000, "Ksh. 96,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Diploma in Fisheries and Aquaculture", "AAS"),
            ("Diploma in Agricultural Economics", "AGECO"),
            ("Diploma in Animal Health and Production", "AGRSCI"),
            ("Diploma in Animal Science and Technology", "AGRSCI"),
        ),
        level="diploma",
        mode_of_study="full_time",
        duration="2-3 years",
        entry_requirements="KCSE mean grade C (Plain) or C- depending on the specific agriculture diploma, or a relevant certificate in the published pathway.",
        fees_structure=_fees(63400, "Ksh. 63,400 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Certificate in General Agriculture", "AGRSCI"),
            ("Certificate in Integrated Agriculture", "AGRSCI"),
            ("Certificate in Animal Health and Production", "AGRSCI"),
            ("Certificate in Animal Science and Technology", "AGRSCI"),
            ("Certificate Course in Environmental Impact Assessment", "NRES"),
            ("Certificate in Fisheries and Aquaculture", "AAS"),
        ),
        level="certificate",
        mode_of_study="full_time",
        duration="1-2 years",
        entry_requirements="KCSE mean grade D+ or C- depending on the specific agriculture certificate, with the published biology or related subject thresholds where applicable.",
        fees_structure=_fees(63000, "Ksh. 63,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("PhD in Political Science", "PSPS"),
            ("PhD in Sociology", "SGDS"),
            ("PhD in Development Studies", "SGDS"),
            ("PhD in Leadership and Governance", "PSPS"),
            ("PhD in Disaster Management", "PSPS"),
            ("PhD in Counseling Psychology", "PSY"),
            ("PhD in Peace and Conflict Studies", "PSPS"),
            ("PhD in Project Planning and Management", "PSPS"),
            ("PhD in Religion", "PRS"),
            ("PhD in Literature", "LLL"),
            ("PhD in Linguistics", "LLL"),
            ("PhD in Kiswahili", "LLL"),
            ("PhD in History", "HH"),
            ("PhD in Geography", "GEOG"),
            ("PhD in Gender and Development Studies", "SGDS"),
        ),
        level="phd",
        mode_of_study="full_time_part_time",
        duration="3 years",
        entry_requirements="Holder of a master's degree in a relevant field or its equivalent from a recognized institution or university.",
        fees_structure=_fees(150000, "Ksh. 150,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("MA in History", "HH"),
            ("MA in Geography", "GEOG"),
            ("MA in Religious Studies", "PRS"),
            ("MA in Literature", "LLL"),
            ("MA in Linguistics", "LLL"),
            ("MA in Kiswahili", "LLL"),
            ("MA in International Relations", "PSPS"),
            ("MA in Public Administration and Public Policy", "PSPS"),
            ("MA in Public Administration and Political Science", "PSPS"),
            ("MA in Criminology", "PSPS"),
            ("MA in Project Planning and Management", "PSPS"),
            ("MA in Development Studies", "SGDS"),
            ("MA in Sociology", "SGDS"),
            ("MA in Counseling Psychology", "PSY"),
            ("MA in Gender and Development Studies", "SGDS"),
        ),
        level="masters",
        mode_of_study="full_time_part_time",
        duration="2 years",
        entry_requirements="Bachelor of Arts degree in a related field with Second Class Upper or Lower with two years working experience.",
        fees_structure=_fees(100000, "Ksh. 100,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Arts", "LLL"),
            ("Bachelor of Arts (Kiswahili)", "LLL"),
            ("Bachelor of Arts (Literature)", "LLL"),
            ("Bachelor of Arts (Linguistics)", "LLL"),
            ("Bachelor of Arts (Social Work and Sociology)", "SGDS"),
            ("Bachelor of Arts (Criminology and Security Studies)", "PSPS"),
            ("Bachelor of Arts (Geography)", "GEOG"),
            ("Bachelor of Arts (History)", "HH"),
            ("Bachelor of Arts (Public Administration and Political Science)", "PSPS"),
            ("Bachelor of Arts (Peace and Conflict Studies)", "PSPS"),
            ("Bachelor of Arts (Community Development)", "SGDS"),
            ("Bachelor of Arts (Psychology)", "PSY"),
            ("Bachelor of Arts (Counseling Psychology)", "PSY"),
            ("Bachelor of Arts (Gender and Development Studies)", "SGDS"),
            ("Bachelor of Arts (Religious Studies)", "PRS"),
            ("Bachelor of Arts in Music", "CPA"),
            ("Bachelor of Arts (Economics and Sociology)", "SGDS"),
        ),
        level="undergraduate",
        mode_of_study="full_time",
        duration="4 years",
        entry_requirements="KCSE mean grade C+ with the subject minimums published for the specific arts and social sciences pathway, or a related diploma where the brochure provides progression.",
        fees_structure=_fees(88000, "Ksh. 88,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Diploma in Criminology and Security Studies", "PSPS"),
            ("Diploma in Public Administration", "PSPS"),
            ("Diploma in County Governance and Management", "PSPS"),
            ("Diploma in Social Work and Community Development", "SGDS"),
            ("Diploma in Music", "CPA"),
            ("Diploma in International Relations, Peace and Conflict Resolutions", "PSPS"),
            ("Diploma in Gender and Development Studies", "SGDS"),
            ("Diploma in Counseling Psychology", "PSY"),
        ),
        level="diploma",
        mode_of_study="full_time",
        duration="2 years",
        entry_requirements="KCSE mean grade C- or its equivalent, or a certificate in a related field from a recognized institution.",
        fees_structure=_fees(54000, "Ksh. 54,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Certificate in Music", "CPA"),
            ("Certificate in Social Work", "SGDS"),
            ("Certificate in Disaster Management", "PSPS"),
            ("Certificate in Public Administration", "PSPS"),
            ("Certificate in Criminology and Security Studies", "PSPS"),
            ("Certificate in County Governance and Management", "PSPS"),
            ("Certificate in Counseling Psychology", "PSY"),
        ),
        level="certificate",
        mode_of_study="full_time",
        duration="1 year",
        entry_requirements="KCSE mean grade D+ or its equivalent.",
        fees_structure=_fees(36500, "Ksh. 36,500 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("PhD in Physics", "PHYS"),
            ("PhD in Mathematical Statistics", "MATHACT"),
            ("PhD in Applied Mathematics", "MATHACT"),
            ("PhD in Pure Mathematics", "MATHACT"),
            ("PhD in Analytical Chemistry", "CHEM"),
            ("PhD in Organic Chemistry", "CHEM"),
            ("PhD in Parasitology", "BIO"),
        ),
        level="phd",
        mode_of_study="part_time",
        duration="3 years",
        entry_requirements="Holder of a master's degree in a relevant field or its equivalent from a recognized university or institution.",
        fees_structure=_fees(150000, "Ksh. 150,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("MSc in Animal Physiology", "BIO"),
            ("MSc in Plant Pathology", "BIO"),
            ("MSc in Analytical Chemistry", "CHEM"),
            ("MSc in Organic Chemistry", "CHEM"),
            ("MSc in Inorganic Chemistry", "CHEM"),
            ("MSc in Pure Mathematics", "MATHACT"),
            ("MSc in Applied Mathematics", "MATHACT"),
            ("MSc in Parasitology", "BIO"),
            ("MSc in Mathematical Statistics", "MATHACT"),
            ("MSc in Physics", "PHYS"),
            ("MSc in Phytochemistry and Drug Development", "CHEM"),
            ("MSc in Medicinal Ethnobotany", "BIO"),
            ("MSc in Physical Chemistry", "CHEM"),
            ("MSc in Renewable Energy Physics", "PHYS"),
            ("MSc in Environmental Physics", "PHYS"),
        ),
        level="masters",
        mode_of_study="full_time_part_time",
        duration="2 years",
        entry_requirements="Holder of a Bachelor of Science degree in a related field or equivalent with Second Class Upper Division or Lower Division plus two years experience in a relevant field.",
        fees_structure=_fees(120000, "Ksh. 120,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Science in Chemistry", "CHEM"),
            ("Bachelor of Science in Physics", "PHYS"),
            ("Bachelor of Science in Applied Statistics", "MATHACT"),
            ("Bachelor of Science in Mathematics with Computing", "MATHACT"),
            ("Bachelor of Science in Biometry and Informatics", "MATHACT"),
            ("Bachelor of Science in Mathematics (Pure, Applied and Statistics)", "MATHACT"),
            ("Bachelor of Science in Biology", "BIO"),
            ("Bachelor of Science in Biochemistry", "BIO"),
            ("Bachelor of Science in Microbiology", "BIO"),
            ("Bachelor of Science in Biotechnology", "BIO"),
            ("Bachelor of Science in Cellular and Molecular Biology", "BIO"),
            ("Bachelor of Science in Petroleum Chemistry", "CHEM"),
            ("Bachelor of Science in Renewable Energy", "PHYS"),
            ("Bachelor of Science in Industrial Chemistry", "CHEM"),
            ("Bachelor of Science in Conservation Biology", "BIO"),
            ("Bachelor of Science in Forensic Biology", "BIO"),
            ("Bachelor of Science in Environmental Chemistry", "CHEM"),
            ("Bachelor of Science in Analytical Chemistry", "CHEM"),
            ("Bachelor of Science in Natural Products", "CHEM"),
            ("Bachelor of Science in Geophysics and Mineralogy", "PHYS"),
            ("Bachelor of Science in Waste Management", "CHEM"),
            ("Bachelor of Actuarial Science", "MATHACT"),
            ("Bachelor of Science in Laboratory Science and Technology", "BIO"),
        ),
        level="undergraduate",
        mode_of_study="full_time",
        duration="4 years",
        entry_requirements="KCSE mean grade C+ with the subject cluster and diploma progression routes published for the respective pure and applied sciences programme.",
        fees_structure=_fees(96000, "Ksh. 96,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Post Graduate Diploma in Sciences", "BIO"),
        ),
        level="postgraduate_diploma",
        mode_of_study="full_time",
        duration="1 year",
        entry_requirements="Bachelor's degree in a related field.",
        fees_structure=_fees(70000, "Ksh. 70,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Diploma in E-Waste Management", "PHYS"),
            ("Diploma in Forensic Biology", "BIO"),
            ("Diploma in Forensic Chemistry", "CHEM"),
            ("Diploma in Science Laboratory Technology", "BIO"),
        ),
        level="diploma",
        mode_of_study="full_time",
        duration="2 years",
        entry_requirements="KCSE mean grade C- or C depending on the specific pure and applied sciences diploma, or a relevant certificate or craft course where the brochure allows progression.",
        fees_structure=_fees(63400, "Ksh. 63,400 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("PhD in Biomedical Sciences", "AHS"),
        ),
        level="phd",
        mode_of_study="part_time",
        duration="3 years",
        entry_requirements="Holder of an MSc in a medical-related field.",
        fees_structure=_fees(150000, "Ksh. 150,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("MSc in Biomedical Sciences", "AHS"),
            ("Master of Public Health", "PUBH"),
            ("MSc in Nutrition", "FND"),
        ),
        level="masters",
        mode_of_study="part_time",
        duration="2 years",
        entry_requirements="Bachelor of Science in a related field from a recognized institution.",
        fees_structure=_fees(120000, "Ksh. 120,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Science in Clinical Medicine and Surgery (Upgrading)", "CLMED"),
        ),
        level="undergraduate",
        mode_of_study="part_time",
        duration="2.5 years",
        entry_requirements="KCSE C (Plain) or equivalent and a diploma in Clinical Medicine and Surgery from a recognized institution, with registration by the Clinical Officers Council.",
        fees_structure=_fees(180000, "Ksh. 180,000 per year"),
        intake_months=("September",),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Science in Nursing (Upgrading)", "NURS"),
        ),
        level="undergraduate",
        mode_of_study="part_time",
        duration="3 years",
        entry_requirements="KCSE C (Plain) or equivalent and a recognized practicing nursing qualification registered with the Nursing Council of Kenya or equivalent regulator.",
        fees_structure=_fees(180000, "Ksh. 180,000 per year"),
        intake_months=("May", "September"),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Science in Nursing (Direct Entry)", "NURS"),
        ),
        level="undergraduate",
        mode_of_study="full_time",
        duration="4 years",
        entry_requirements="KCSE C+ with C+ in Mathematics or Physics, English or Kiswahili, Biology, and Chemistry.",
        fees_structure=_fees(220000, "Ksh. 220,000 per year"),
        intake_months=("September",),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Food Nutrition and Dietetics", "FND"),
            ("Bachelor of Biomedical Science and Technology", "AHS"),
            ("Bachelor of Science in Public Health", "PUBH"),
            ("Bachelor of Science in Community Health and Development", "CHD"),
            ("Bachelor of Science in Medical Laboratory Science", "MLS"),
        ),
        level="undergraduate",
        mode_of_study="full_time",
        duration="4 years",
        entry_requirements="KCSE mean grade C+ with C+ in Biology, Chemistry, and Mathematics or Physics, and English or Kiswahili.",
        fees_structure=_fees(96000, "Ksh. 96,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Science in Clinical Medicine and Surgery (Direct Entry)", "CLMED"),
        ),
        level="undergraduate",
        mode_of_study="full_time",
        duration="4 years",
        entry_requirements="KCSE mean grade C+ with C Plain in Biology, Chemistry, Mathematics or Physics, and Kiswahili or English.",
        fees_structure=_fees(96100, "Ksh. 96,100 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Pharmacy", "PHARM"),
        ),
        level="undergraduate",
        mode_of_study="full_time",
        duration="5 years",
        entry_requirements="As prescribed from time to time by the professional regulator and approved by the University Senate.",
        fees_structure=_fees(400000, "Ksh. 400,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Diploma in Clinical Medicine and Surgery", "CLMED"),
            ("Diploma in Medical Laboratory Sciences", "MLS"),
            ("Diploma in Pharmaceutical Technology", "PHARM"),
            ("Diploma in Community Health and Development", "CHD"),
            ("Diploma in Health Records and Information Technology", "PUBH"),
            ("Diploma in Community Nutrition and Dietetics", "FND"),
        ),
        level="diploma",
        mode_of_study="full_time",
        duration="2-3 years",
        entry_requirements="KCSE mean grade C (Plain) with the subject thresholds published for the specific health sciences diploma, or a relevant certificate and work experience where the brochure allows progression.",
        fees_structure=_fees(81000, "Ksh. 81,000 per year"),
        intake_months=("September",),
    ),
    *_expand_programmes(
        programmes=(
            ("PhD in Business Administration", "BUSADM"),
            ("PhD in Procurement and Logistics Management", "MSC"),
            ("PhD in Tourism Management", "THM"),
            ("PhD in Entrepreneurship and Management", "BUSADM"),
            ("PhD in Economics", "ECONSTAT"),
        ),
        level="phd",
        mode_of_study="full_time_part_time",
        duration="3 years",
        entry_requirements="Holder of a master's degree in a relevant field or its equivalent from a recognized institution or university.",
        fees_structure=_fees(150000, "Ksh. 150,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Master in Human Resource", "HRSM"),
            ("Master of Business Administration", "BUSADM"),
            ("MSc in Economics", "ECONSTAT"),
            ("MSc in Project Management, Monitoring and Evaluation", "BUSADM"),
            ("MSc in Finance and Investment", "ACCFIN"),
            ("MSc in Procurement and Logistics Management", "MSC"),
            ("Master of Purchasing and Logistics Management", "MSC"),
            ("MSc in Entrepreneurship and Management", "BUSADM"),
            ("MSc in Marketing", "BUSADM"),
            ("Master of Tourism and Hospitality Management", "THM"),
            ("Master of Entrepreneurship", "BUSADM"),
        ),
        level="masters",
        mode_of_study="full_time_part_time",
        duration="2 years",
        entry_requirements="Bachelor's degree with at least Second Class Upper and above, or Second Class Lower with at least two years experience from the date of graduation.",
        fees_structure=_fees(100000, "Ksh. 100,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Commerce", "ACCFIN"),
            ("Bachelor of Entrepreneurship and Management", "BUSADM"),
            ("Bachelor of Purchasing and Supplies Management", "MSC"),
            ("Bachelor of Cooperative Management", "BUSADM"),
            ("Bachelor of Business Information Management", "BUSADM"),
            ("Bachelor of Human Resource Management", "HRSM"),
            ("Bachelor of Secretarial Management and Administration", "BUSADM"),
            ("Bachelor of Science in Project Management", "BUSADM"),
            ("Bachelor of Tourism and Hospitality Management", "THM"),
            ("Bachelor of Hotel and Hospitality Management", "THM"),
            ("Bachelor of Tours and Travel Management", "THM"),
            ("Bachelor of Business and Management", "BUSADM"),
        ),
        level="undergraduate",
        mode_of_study="full_time",
        duration="4 years",
        entry_requirements="KCSE mean grade C+ with C Plain in Mathematics and English or Kiswahili, or diploma progression from a recognized institution where specified.",
        fees_structure=_fees(88000, "Ksh. 88,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Science in Economics and Statistics", "ECONSTAT"),
        ),
        level="undergraduate",
        mode_of_study="full_time",
        duration="4 years",
        entry_requirements="KCSE mean grade C+ with C+ in Mathematics or Economics, Commerce, Accounting, or Business Studies, or a recognized bridging course in Mathematics.",
        fees_structure=_fees(96000, "Ksh. 96,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Diploma in Business Administration", "BUSADM"),
            ("Diploma in Sales and Marketing", "BUSADM"),
            ("Diploma in Human Resource Management", "HRSM"),
            ("Diploma in Marketing Management", "BUSADM"),
            ("Diploma in Co-operative Management", "BUSADM"),
            ("Diploma in Hotel and Hospitality Management", "THM"),
            ("Diploma in Tours and Hospitality Management", "THM"),
            ("Diploma in Project Management", "BUSADM"),
            ("Diploma in County Leadership Management", "BUSADM"),
            ("Diploma in Secretarial Management", "BUSADM"),
            ("Diploma in Procurement and Logistics Management", "MSC"),
            ("Diploma in Accounting and Finance", "ACCFIN"),
            ("Diploma in Credit Management", "ACCFIN"),
            ("Diploma in Risk Management", "ACCFIN"),
            ("Diploma in Financial Analysis", "ACCFIN"),
            ("Diploma in Tax Consultancy", "ACCFIN"),
            ("Diploma in Business Information Technology", "BUSADM"),
        ),
        level="diploma",
        mode_of_study="full_time",
        duration="2 years",
        entry_requirements="KCSE mean grade C- with the mathematics and English thresholds published for the specific business diploma, or a relevant certificate with credit pass from a recognized institution.",
        fees_structure=_fees(54000, "Ksh. 54,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Certificate in Sales and Marketing", "BUSADM"),
            ("Certificate in Human Resource Management", "HRSM"),
            ("Certificate in Stores and Supplies Management", "MSC"),
            ("Certificate in Project Management", "BUSADM"),
            ("Certificate in Business Administration", "BUSADM"),
            ("Certificate in Marketing Management", "BUSADM"),
            ("Certificate in Co-operative Management", "BUSADM"),
            ("Certificate in Hotel and Hospitality Management", "THM"),
            ("Certificate in Accounting and Finance", "ACCFIN"),
            ("Certificate in Secretarial Management and Administration", "BUSADM"),
            ("Certificate in Risk Management", "ACCFIN"),
            ("Certificate in Credit Management", "ACCFIN"),
            ("Certificate in Financial Analysis", "ACCFIN"),
            ("Certificate in Tax Consultancy", "ACCFIN"),
        ),
        level="certificate",
        mode_of_study="full_time",
        duration="1 year",
        entry_requirements="KCSE mean grade D+ or its equivalent.",
        fees_structure=_fees(36500, "Ksh. 36,500 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("PhD in Information Science", "COMLIS"),
            ("PhD in Information Systems", "CS"),
            ("PhD in Knowledge Management", "COMLIS"),
            ("PhD in Media and Communication Studies", "COMLIS"),
        ),
        level="phd",
        mode_of_study="part_time",
        duration="3 years",
        entry_requirements="Holder of a master's degree in a relevant field or its equivalent from a recognized institution or university.",
        fees_structure=_fees(150000, "Ksh. 150,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Master of Information Science", "COMLIS"),
            ("Master of Knowledge Management", "COMLIS"),
            ("Master of Information Systems", "CS"),
            ("Master of Journalism", "COMLIS"),
            ("Master of Communication Studies", "COMLIS"),
        ),
        level="masters",
        mode_of_study="part_time",
        duration="2 years",
        entry_requirements="Second Class Upper Division and above, or Lower Division with at least two years experience from the date of graduation.",
        fees_structure=_fees(100000, "Ksh. 100,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Bachelor of Science in Applied Computer Science", "CS"),
            ("Bachelor of Science in Computer Science", "CS"),
            ("Bachelor of Science in Software Engineering", "CS"),
            ("Bachelor of Science in Information Technology", "CS"),
            ("Bachelor of Information Science", "COMLIS"),
            ("Bachelor of Arts (Communication and Media)", "COMLIS"),
        ),
        level="undergraduate",
        mode_of_study="full_time",
        duration="4 years",
        entry_requirements="KCSE mean grade C+ with the Mathematics, Physics, English, or Kiswahili thresholds published for the respective information science and technology programme, or a related diploma progression route.",
        fees_structure=_fees(96000, "Ksh. 96,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Diploma in Information Technology", "CS"),
            ("Diploma in Library and Information Science", "COMLIS"),
            ("Diploma in Journalism and Mass Communication", "COMLIS"),
            ("Diploma in Computer Science", "CS"),
        ),
        level="diploma",
        mode_of_study="full_time",
        duration="2 years",
        entry_requirements="KCSE mean grade C- or C Plain with the published subject thresholds, or a relevant certificate in a related field.",
        fees_structure=_fees(54000, "Ksh. 54,000 per year"),
    ),
    *_expand_programmes(
        programmes=(
            ("Certificate in Information Technology", "CS"),
            ("Certificate in Library and Information Science", "COMLIS"),
            ("Certificate in Journalism and Mass Communication", "COMLIS"),
        ),
        level="certificate",
        mode_of_study="full_time",
        duration="1 year",
        entry_requirements="KCSE mean grade D+ or its equivalent.",
        fees_structure=_fees(36500, "Ksh. 36,500 per year"),
    ),
]
