"""Seed explicit reporting chains via StaffAssignment."""

from __future__ import annotations

from sqlalchemy.ext.asyncio import AsyncSession

from ._shared import LEADERSHIP_PEOPLE, SeedContext, get_or_create_person, upsert_staff_assignment


async def seed_staff_assignments(db: AsyncSession, ctx: SeedContext) -> None:
    for key, spec in LEADERSHIP_PEOPLE.items():
        if key not in ctx.people:
            await get_or_create_person(db, ctx, key, **spec)

    council = ctx.boards["COUNCIL"]
    management = ctx.boards["MANAGEMENT"]
    ovc = ctx.divisions["OVC"]
    apf = ctx.divisions["APF"]
    arsa = ctx.divisions["ARSA"]
    ahrcs = ctx.wings["AHRCS"]
    finance = ctx.wings["FIN"]
    academic_affairs = ctx.wings["RAA"]
    reirm = ctx.wings["REIRM"]
    student_affairs = ctx.wings["STUAFFAIRS"]
    ict = ctx.departments["ICT"]
    school_codes = {
        "dean_agriculture": "SANRM",
        "dean_business": "SBE",
        "dean_education": "SEHRD",
        "dean_health": "SHS",
        "dean_ist": "SIST",
        "dean_pure_sciences": "SPAS",
        "dean_arts": "SASS",
        "dean_law": "SOL",
    }

    chair_assignment = await upsert_staff_assignment(
        db,
        ctx,
        "council-chair",
        person_id=ctx.people["council_chair"].id,
        user_id=None,
        entity_type="board",
        entity_id=council.id,
        role="chairperson",
        title="University Council Chairperson",
        hierarchy_level=1,
        reports_to_id=None,
        is_primary=True,
        is_acting=False,
        is_public=True,
        status="active",
        display_order=1,
        notes="Top-level governance authority.",
    )

    await upsert_staff_assignment(
        db,
        ctx,
        "council-secretary",
        person_id=ctx.people["vice_chancellor"].id,
        user_id=None,
        entity_type="board",
        entity_id=council.id,
        role="secretary",
        title="Secretary to the University Council",
        hierarchy_level=4,
        reports_to_id=chair_assignment.id,
        is_primary=False,
        is_acting=False,
        is_public=True,
        status="active",
        display_order=2,
        notes="Board assignment for the Vice Chancellor.",
    )

    for idx, key in enumerate(
        (
            "council_member_peter_mageto",
            "council_member_scholastica_ndambuki",
            "council_member_elizabeth_mwangi",
            "council_member_samson_muchelule",
            "council_member_mwenda_makathimo",
            "council_member_pamela_awuor_ochieng",
            "council_member_josphat_sawe",
        ),
        start=10,
    ):
        await upsert_staff_assignment(
            db,
            ctx,
            f"council-member-{idx}",
            person_id=ctx.people[key].id,
            user_id=None,
            entity_type="board",
            entity_id=council.id,
            role="member",
            title="University Council Member",
            hierarchy_level=2,
            reports_to_id=chair_assignment.id,
            is_primary=False,
            is_acting=False,
            is_public=True,
            status="active",
            display_order=idx,
            notes="Council membership seeded from public governance listing.",
        )

    vc_assignment = await upsert_staff_assignment(
        db,
        ctx,
        "vc-university",
        person_id=ctx.people["vice_chancellor"].id,
        user_id=None,
        entity_type="university",
        entity_id=None,
        role="vc",
        title="Vice Chancellor",
        hierarchy_level=2,
        reports_to_id=chair_assignment.id,
        is_primary=True,
        is_acting=False,
        is_public=True,
        status="active",
        display_order=1,
        notes="Institutional executive role.",
    )

    dvc_apf_assignment = await upsert_staff_assignment(
        db,
        ctx,
        "dvc-apf",
        person_id=ctx.people["dvc_apf"].id,
        user_id=None,
        entity_type="division",
        entity_id=apf.id,
        role="dvc",
        title="Deputy Vice Chancellor, Administration, Planning & Finance",
        hierarchy_level=3,
        reports_to_id=vc_assignment.id,
        is_primary=True,
        is_acting=False,
        is_public=True,
        status="active",
        display_order=1,
        notes=None,
    )
    dvc_arsa_assignment = await upsert_staff_assignment(
        db,
        ctx,
        "dvc-arsa",
        person_id=ctx.people["dvc_arsa"].id,
        user_id=None,
        entity_type="division",
        entity_id=arsa.id,
        role="dvc",
        title="Deputy Vice Chancellor, Academic, Research & Student Affairs",
        hierarchy_level=3,
        reports_to_id=vc_assignment.id,
        is_primary=True,
        is_acting=False,
        is_public=True,
        status="active",
        display_order=2,
        notes=None,
    )
    await upsert_staff_assignment(
        db,
        ctx,
        "vc-management-chair",
        person_id=ctx.people["vice_chancellor"].id,
        user_id=None,
        entity_type="board",
        entity_id=management.id,
        role="chairperson",
        title="Chairperson, Management Board",
        hierarchy_level=2,
        reports_to_id=vc_assignment.id,
        is_primary=False,
        is_acting=False,
        is_public=True,
        status="active",
        display_order=1,
        notes=None,
    )
    for idx, key in enumerate(
        (
            "dvc_apf",
            "dvc_arsa",
            "registrar_admin",
            "registrar_academic",
            "research_director",
            "finance_officer",
        ),
        start=2,
    ):
        await upsert_staff_assignment(
            db,
            ctx,
            f"management-member-{key}",
            person_id=ctx.people[key].id,
            user_id=None,
            entity_type="board",
            entity_id=management.id,
            role="member",
            title="Management Board Member",
            hierarchy_level=4 if "registrar" in key or key == "finance_officer" else 3,
            reports_to_id=vc_assignment.id,
            is_primary=False,
            is_acting=False,
            is_public=True,
            status="active",
            display_order=idx,
            notes="Management Board membership seeded from public university management listing.",
        )

    registrar_admin_assignment = await upsert_staff_assignment(
        db,
        ctx,
        "registrar-admin",
        person_id=ctx.people["registrar_admin"].id,
        user_id=None,
        entity_type="wing",
        entity_id=ahrcs.id,
        role="registrar",
        title="Ag. Registrar AHRCS",
        hierarchy_level=4,
        reports_to_id=dvc_apf_assignment.id,
        is_primary=True,
        is_acting=True,
        is_public=True,
        status="active",
        display_order=1,
        notes=None,
    )
    registrar_academic_assignment = await upsert_staff_assignment(
        db,
        ctx,
        "registrar-academic",
        person_id=ctx.people["registrar_academic"].id,
        user_id=None,
        entity_type="wing",
        entity_id=academic_affairs.id,
        role="registrar",
        title="Ag. Registrar AA",
        hierarchy_level=4,
        reports_to_id=dvc_arsa_assignment.id,
        is_primary=True,
        is_acting=True,
        is_public=True,
        status="active",
        display_order=1,
        notes=None,
    )
    research_assignment = await upsert_staff_assignment(
        db,
        ctx,
        "registrar-reirm",
        person_id=ctx.people["research_director"].id,
        user_id=None,
        entity_type="wing",
        entity_id=reirm.id,
        role="registrar",
        title="Ag. Registrar REIRM",
        hierarchy_level=4,
        reports_to_id=dvc_arsa_assignment.id,
        is_primary=True,
        is_acting=True,
        is_public=True,
        status="active",
        display_order=2,
        notes=None,
    )
    finance_assignment = await upsert_staff_assignment(
        db,
        ctx,
        "finance-officer",
        person_id=ctx.people["finance_officer"].id,
        user_id=None,
        entity_type="wing",
        entity_id=finance.id,
        role="finance_officer",
        title="Finance Officer",
        hierarchy_level=4,
        reports_to_id=dvc_apf_assignment.id,
        is_primary=True,
        is_acting=False,
        is_public=True,
        status="active",
        display_order=2,
        notes=None,
    )

    await upsert_staff_assignment(
        db,
        ctx,
        "dean-students",
        person_id=ctx.people["dean_students"].id,
        user_id=None,
        entity_type="wing",
        entity_id=student_affairs.id,
        role="director",
        title="Dean of Students",
        hierarchy_level=5,
        reports_to_id=dvc_arsa_assignment.id,
        is_primary=True,
        is_acting=False,
        is_public=True,
        status="active",
        display_order=1,
        notes=None,
    )
    await upsert_staff_assignment(
        db,
        ctx,
        "librarian",
        person_id=ctx.people["university_librarian"].id,
        user_id=None,
        entity_type="department",
        entity_id=ctx.departments["LIB"].id,
        role="librarian",
        title="University Librarian",
        hierarchy_level=5,
        reports_to_id=registrar_academic_assignment.id,
        is_primary=True,
        is_acting=False,
        is_public=True,
        status="active",
        display_order=2,
        notes=None,
    )
    await upsert_staff_assignment(
        db,
        ctx,
        "elearning-director",
        person_id=ctx.people["director_elearning"].id,
        user_id=None,
        entity_type="department",
        entity_id=ctx.departments["ELEARN"].id,
        role="director",
        title="Director, E-Learning",
        hierarchy_level=5,
        reports_to_id=dvc_arsa_assignment.id,
        is_primary=True,
        is_acting=False,
        is_public=True,
        status="active",
        display_order=3,
        notes=None,
    )

    for dean_key, school_code in school_codes.items():
        await upsert_staff_assignment(
            db,
            ctx,
            f"school-{school_code}-dean",
            person_id=ctx.people[dean_key].id,
            user_id=None,
            entity_type="school",
            entity_id=ctx.schools[school_code].id,
            role="dean",
            title=f"Dean, {ctx.schools[school_code].name}",
            hierarchy_level=5,
            reports_to_id=registrar_academic_assignment.id,
            is_primary=True,
            is_acting=False,
            is_public=True,
            status="active",
            display_order=10,
            notes=None,
        )

    ict_manager_assignment = await upsert_staff_assignment(
        db,
        ctx,
        "ict-manager",
        person_id=ctx.people["ict_manager"].id,
        user_id=None,
        entity_type="department",
        entity_id=ict.id,
        role="director",
        title="ICT Manager",
        hierarchy_level=5,
        reports_to_id=dvc_apf_assignment.id,
        is_primary=True,
        is_acting=False,
        is_public=True,
        status="active",
        display_order=1,
        notes="Operational head of the ICT Department.",
    )

    ict_chain = [
        ("ict-cyber", "ict_cybersecurity_head", "ICT-CYBER", "head", "Section Head, Cybersecurity and User Support", 6),
        ("ict-softdev", "ict_software_dev_head", "ICT-SOFTDEV", "head", "Section Head, Software Development", 6),
        ("ict-install", "ict_installation_maintenance_head", "ICT-INSTALL", "head", "Section Head, Installation and Maintenance", 6),
        ("ict-net", "ict_networking_head", "ICT-NET", "head", "Section Head, Networking and Connectivity", 6),
        ("ict-web", "ict_website_support_head", "ICT-WEB", "head", "Section Head, Website Support", 6),
    ]
    for key, person_key, department_code, role, title, level in ict_chain:
        await upsert_staff_assignment(
            db,
            ctx,
            key,
            person_id=ctx.people[person_key].id,
            user_id=None,
            entity_type="department",
            entity_id=ctx.departments[department_code].id,
            role=role,
            title=title,
            hierarchy_level=level,
            reports_to_id=ict_manager_assignment.id,
            is_primary=True,
            is_acting=False,
            is_public=True,
            status="active",
            display_order=20,
            notes=None,
        )

    software_head_assignment = ctx.assignments["ict-softdev"]
    await upsert_staff_assignment(
        db,
        ctx,
        "ict-staff-leakey",
        person_id=ctx.people["ict_officer_leakey_namoyo"].id,
        user_id=None,
        entity_type="department",
        entity_id=ctx.departments["ICT-SOFTDEV"].id,
        role="staff",
        title="Software Developer",
        hierarchy_level=8,
        reports_to_id=software_head_assignment.id,
        is_primary=True,
        is_acting=False,
        is_public=True,
        status="active",
        display_order=30,
        notes=None,
    )
    await upsert_staff_assignment(
        db,
        ctx,
        "ict-staff-robline",
        person_id=ctx.people["ict_officer_robline_yegon"].id,
        user_id=None,
        entity_type="department",
        entity_id=ctx.departments["ICT-SOFTDEV"].id,
        role="staff",
        title="Software Developer",
        hierarchy_level=8,
        reports_to_id=software_head_assignment.id,
        is_primary=True,
        is_acting=False,
        is_public=True,
        status="active",
        display_order=31,
        notes=None,
    )
