#!/usr/bin/env bash
set -Eeuo pipefail

: "${BACKUP_FILE:?BACKUP_FILE is required}"
: "${RECOVERY_DB:?RECOVERY_DB is required}"
: "${RECOVERY_USER:?RECOVERY_USER is required}"

BACKUP_FILE="${BACKUP_FILE}" \
POSTGRES_CONTAINER="${RECOVERY_CONTAINER:-}" \
POSTGRES_HOST="${RECOVERY_HOST:-127.0.0.1}" \
POSTGRES_PORT="${RECOVERY_PORT:-5432}" \
POSTGRES_PASSWORD="${RECOVERY_PASSWORD:-}" \
POSTGRES_DB="${RECOVERY_DB}" \
POSTGRES_USER="${RECOVERY_USER}" \
ALLOW_DESTRUCTIVE_RESTORE=yes \
scripts/restore_database.sh

POSTGRES_DB="${RECOVERY_DB}" \
DATABASE_ADMIN_USER="${RECOVERY_USER}" \
DATABASE_ADMIN_PASSWORD="${RECOVERY_PASSWORD:-}" \
DATABASE_HOST="${RECOVERY_HOST:-127.0.0.1}" \
DATABASE_PORT="${RECOVERY_PORT:-5432}" \
MAIN_DB_PASSWORD="${MAIN_DB_PASSWORD:?MAIN_DB_PASSWORD is required}" \
RESEARCH_DB_PASSWORD="${RESEARCH_DB_PASSWORD:?RESEARCH_DB_PASSWORD is required}" \
LIBRARY_DB_PASSWORD="${LIBRARY_DB_PASSWORD:?LIBRARY_DB_PASSWORD is required}" \
HERI_DB_PASSWORD="${HERI_DB_PASSWORD:?HERI_DB_PASSWORD is required}" \
scripts/init-database-ownership.sh >/dev/null

DATABASE_ADMIN_URL="${RECOVERY_ADMIN_URL:?RECOVERY_ADMIN_URL is required}" scripts/verify_database_recovery.py
DATABASE_ADMIN_URL="${RECOVERY_ADMIN_URL}" scripts/verify_database_ownership.py
echo "restore drill completed"
