"use client";

import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import { Button } from "@ksu/ui/components";
import { SourceRecordPicker } from "@/components/page-cms/source-record-picker";
import { EditorActions, SharedSectionFields, createReferenceItem, itemLimitError, moveRow, sourcePickerValue, useTypedSectionEditor, type SectionEditorProps, type TypedSectionDraft } from "./shared-section-fields";

export function EventsEditor(props: SectionEditorProps) {
  const editor = useTypedSectionEditor({ ...props, ownedSettingKeys: [] });
  const items = editor.draft.items.filter((item) => item.item_type === "reference");
  const limitReached = items.length >= props.definition.max_items;
  const updateItems = (next: typeof items) => editor.setDraft((current) => ({ ...current, items: next.map((item, index) => ({ ...item, display_order: (index + 1) * 10 })) }));
  const validate = (draft: TypedSectionDraft) => itemLimitError(draft.items.filter((item) => item.is_enabled !== false).length, props.definition.min_items, props.definition.max_items, "Event sources");

  return <div className="space-y-5"><SharedSectionFields draft={editor.draft} setDraft={editor.setDraft} readOnly={props.readOnly} /><section aria-label="Event sources" className="space-y-3 border-t border-border pt-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-sm font-semibold">Event sources</h3><p className="mt-1 text-sm text-muted-foreground">Only event records available to this page scope can be selected. Unavailable records remain disabled in the picker.</p></div><Button type="button" variant="outline" size="sm" disabled={props.readOnly || limitReached} onClick={() => updateItems([...items, { item_type: "reference", source_type: "event", display_order: (items.length + 1) * 10, is_enabled: true }])}><Plus />Add event</Button></div>{limitReached ? <p className="text-sm text-muted-foreground">The definition allows no more than {props.definition.max_items} event sources. Remove one before selecting another.</p> : null}{items.map((item, index) => <div key={item.id ?? index} className="grid gap-3 border-b border-border pb-3 md:grid-cols-[minmax(0,1fr)_auto]"><SourceRecordPicker sourceType="event" layoutVariant="events_list" scopeType={props.section.scope_type} scopeId={props.section.scope_id} label="Event source" value={sourcePickerValue(props.section, "event", item)} onChange={(value) => value && updateItems(items.map((row, rowIndex) => rowIndex === index ? createReferenceItem("event", value.sourceId, row.display_order ?? 10) : row))} disabled={props.readOnly} /><div className="flex items-end gap-1"><Button type="button" variant="ghost" size="icon" aria-label="Move event up" disabled={props.readOnly || index === 0} onClick={() => updateItems(moveRow(items, index, -1))}><ArrowUp /></Button><Button type="button" variant="ghost" size="icon" aria-label="Move event down" disabled={props.readOnly || index === items.length - 1} onClick={() => updateItems(moveRow(items, index, 1))}><ArrowDown /></Button><Button type="button" variant="ghost" size="icon" aria-label="Remove event" disabled={props.readOnly || items.length <= props.definition.min_items} onClick={() => updateItems(items.filter((_, rowIndex) => rowIndex !== index))}><Trash2 /></Button></div></div>)}</section><EditorActions section={props.section} dirty={editor.dirty} isSaving={editor.isSaving} saveError={editor.saveError} readOnly={props.readOnly} onReset={editor.reset} onSave={() => void editor.save(validate)} /></div>;
}
